import type { Config } from "tailwindcss";

const shadeNames = ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900"] as const;
const themedPaletteNames = [
  "slate",
  "gray",
  "zinc",
  "neutral",
  "stone",
  "red",
  "rose",
  "orange",
  "amber",
  "yellow",
  "green",
  "emerald",
  "lime",
  "teal",
  "blue",
  "sky",
  "cyan",
  "indigo",
  "violet",
  "purple",
  "fuchsia",
  "pink",
] as const;

const themedPalette = Object.fromEntries(
  themedPaletteNames.map((name) => [
    name,
    Object.fromEntries(shadeNames.map((shade) => [shade, `var(--ui-${name}-${shade})`])),
  ])
);

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./lib/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "var(--font-prompt)",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Arial",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Noto Color Emoji",
        ],
      },
      colors: {
        white: "var(--ui-surface)",
        black: "var(--ui-text)",
        ...themedPalette,
        ap: {
          bg: "var(--ap-bg)",
          card: "var(--ap-card)",
          blue: "var(--ap-blue)",
          "blue-h": "var(--ap-blue-h)",
          primary: "var(--ap-primary)",
          secondary: "var(--ap-secondary)",
          tertiary: "var(--ap-tertiary)",
          border: "var(--ap-border)",
          red: "var(--ap-red)",
          green: "var(--ap-green)",
          orange: "var(--ap-orange)",
        },
        "page-bg": "var(--page-bg)",
        "navbar-bg": "var(--navbar-bg)",
        "balance-card-bg": "var(--balance-card-bg)",
        "surface-card": "var(--ap-card)",
        "surface-subtle": "var(--ap-bg)",
        "surface-page": "var(--page-bg)",
        "surface-navbar": "var(--navbar-bg)",
        "surface-highlight": "var(--balance-card-bg)",
        ui: {
          page: "var(--ui-page-bg)",
          surface: "var(--ui-surface)",
          "surface-muted": "var(--ui-surface-muted)",
          "surface-raised": "var(--ui-surface-raised)",
          overlay: "var(--ui-surface-overlay)",
          border: "var(--ui-border)",
          text: "var(--ui-text)",
          "text-muted": "var(--ui-text-muted)",
          "text-soft": "var(--ui-text-soft)",
          "text-inverse": "var(--ui-text-inverse)",
          header: {
            bg: "var(--ui-header-bg)",
            text: "var(--ui-header-text)",
          },
          button: {
            primary: "var(--ui-button-primary-bg)",
            "primary-hover": "var(--ui-button-primary-bg-hover)",
            "primary-text": "var(--ui-button-primary-text)",
            danger: "var(--ui-button-danger-bg)",
            "danger-text": "var(--ui-button-danger-text)",
            secondary: "var(--ui-button-secondary-bg)",
            "secondary-text": "var(--ui-button-secondary-text)",
          },
          selected: {
            bg: "var(--ui-selected-bg)",
            border: "var(--ui-selected-border)",
          },
          status: {
            "success-bg": "var(--ui-status-success-bg)",
            "success-border": "var(--ui-status-success-border)",
            success: "var(--ui-status-success-text)",
            "warning-bg": "var(--ui-status-warning-bg)",
            "warning-border": "var(--ui-status-warning-border)",
            warning: "var(--ui-status-warning-text)",
            "error-bg": "var(--ui-status-error-bg)",
            "error-border": "var(--ui-status-error-border)",
            error: "var(--ui-status-error-text)",
            "info-bg": "var(--ui-status-info-bg)",
            "info-border": "var(--ui-status-info-border)",
            info: "var(--ui-status-info-text)",
          },
          alert: {
            "warning-bg": "var(--ui-alert-warning-bg)",
            "warning-border": "var(--ui-alert-warning-border)",
            warning: "var(--ui-alert-warning-text)",
            "error-bg": "var(--ui-alert-error-bg)",
            "error-border": "var(--ui-alert-error-border)",
            error: "var(--ui-alert-error-text)",
            "info-bg": "var(--ui-alert-info-bg)",
            "info-border": "var(--ui-alert-info-border)",
            info: "var(--ui-alert-info-text)",
          },
          reward: {
            bg: "var(--ui-reward-bg)",
            strong: "var(--ui-reward-bg-strong)",
            text: "var(--ui-reward-text)",
            border: "var(--ui-reward-border)",
          },
          contact: {
            line: "var(--ui-contact-line)",
            telegram: "var(--ui-contact-telegram)",
            default: "var(--ui-contact-default)",
          },
          category: {
            slot: "var(--ui-category-slot)",
            casino: "var(--ui-category-casino)",
            sport: "var(--ui-category-sport)",
            card: "var(--ui-category-card)",
            cock: "var(--ui-category-cock)",
            fish: "var(--ui-category-fish)",
            default: "var(--ui-category-default)",
          },
          balance: {
            text: "var(--ui-balance-text)",
            muted: "var(--ui-balance-muted)",
          },
        },
      },
      borderRadius: { "2xl": "18px", "3xl": "24px", "4xl": "32px" },
      boxShadow: {
        card: "0 2px 8px rgba(0,0,0,0.06), 0 0 1px rgba(0,0,0,0.04)",
        "card-hover": "0 8px 28px rgba(0,0,0,0.09), 0 0 1px rgba(0,0,0,0.04)",
        "card-xl": "0 20px 60px rgba(0,0,0,0.10), 0 0 1px rgba(0,0,0,0.06)",
        "focus-blue": "0 0 0 3px rgba(0,113,227,0.18)",
        "focus-red": "0 0 0 3px rgba(255,59,48,0.15)",
      },
      keyframes: {
        fadeUp: {
          from: { opacity: "0", transform: "translateY(18px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: { from: { opacity: "0" }, to: { opacity: "1" } },
        shake: {
          "0%,100%": { transform: "translateX(0)" },
          "15%": { transform: "translateX(-7px)" },
          "45%": { transform: "translateX(7px)" },
          "65%": { transform: "translateX(-4px)" },
          "85%": { transform: "translateX(4px)" },
        },
        popIn: {
          from: { opacity: "0", transform: "scale(0.92)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        marquee: {
          from: { transform: "translateX(100%)" },
          to:   { transform: "translateX(-100%)" },
        },
      },
      animation: {
        "fade-up": "fadeUp 0.45s cubic-bezier(.25,.46,.45,.94) both",
        "fade-in": "fadeIn 0.3s ease both",
        "fade-in-slow": "fadeIn 1.2s ease both",
        shake: "shake 0.45s ease",
        "pop-in": "popIn 0.35s cubic-bezier(.34,1.56,.64,1) both",
        marquee: "marquee 20s linear 2s infinite",
      },
    },
  },
  plugins: [],
};
export default config;
