// ─── Sub-category item ─────────────────────────────────────────────────────────
export interface SubItem {
  id: string;
  name: string;
  flag: string;
  sub: string;
  isOpen: boolean;
  closeAt?: string;     // ISO 8601 string — ใช้แทน countdown string
  countdown?: string;   // fallback สำหรับ hardcode data
  result?: { top3: string; bot2: string };
  drawStatus?: "resulted" | "open" | "closed" | "pending";
  drawDate?: string;
  barClass: string;
  href: string;
}

// ─── Main category ─────────────────────────────────────────────────────────────
export interface Category {
  id: string;
  label: string;
  emoji: string;
  gradient: string; // Tailwind bg-gradient-to-br classes
  badge: string;
  items: SubItem[];
}

// ─── Data ──────────────────────────────────────────────────────────────────────
export const CATEGORIES: Category[] = [
  {
    id: "thai",
    label: "หวยไทย",
    emoji: "🇹🇭",
    gradient: "from-blue-700 to-red-600",
    badge: "รัฐบาล · ออมสิน · ธ.ก.ส.",
    items: [
      {
        id: "thai_gov",
        name: "หวยรัฐบาล",
        flag: "🇹🇭",
        sub: "งวด 16 มี.ค. 69",
        isOpen: true,
        countdown: "4 วัน 5 ชม.",
        barClass: "from-blue-700 to-red-600",
        href: "/bet?lottery=thai_gov",
      },
      {
        id: "thai_ออมสิน",
        name: "หวยออมสิน",
        flag: "💰",
        sub: "งวด 16 มี.ค. 69",
        isOpen: true,
        countdown: "4 วัน 5 ชม.",
        barClass: "from-green-600 to-emerald-400",
        href: "/bet?lottery=thai_ออมสิน",
      },
      {
        id: "thai_baac",
        name: "หวย ธ.ก.ส.",
        flag: "🌾",
        sub: "งวด 16 มี.ค. 69",
        isOpen: false,
        result: { top3: "481", bot2: "62" },
        barClass: "from-yellow-600 to-lime-400",
        href: "/bet?lottery=thai_baac",
      },
    ],
  },
  {
    id: "foreign",
    label: "หวยต่างประเทศ",
    emoji: "🌏",
    gradient: "from-emerald-600 to-teal-400",
    badge: "ฮานอย · ลาว · มาเลย์",
    items: [
      {
        id: "hanoi_special",
        name: "ฮานอย พิเศษ",
        flag: "🇻🇳",
        sub: "ออกผล 12:00",
        isOpen: false,
        result: { top3: "839", bot2: "47" },
        barClass: "from-red-700 to-yellow-400",
        href: "/bet?lottery=hanoi_special",
      },
      {
        id: "hanoi_1700",
        name: "ฮานอย 17:00",
        flag: "🇻🇳",
        sub: "ออกผล 17:00",
        isOpen: true,
        countdown: "07:23:18",
        barClass: "from-red-600 to-yellow-400",
        href: "/bet?lottery=hanoi_1700",
      },
      {
        id: "hanoi_vip",
        name: "ฮานอย VIP",
        flag: "🇻🇳",
        sub: "ออกผล 18:10",
        isOpen: true,
        countdown: "08:33:18",
        barClass: "from-red-500 to-orange-400",
        href: "/bet?lottery=hanoi_vip",
      },
      {
        id: "hanoi_extra",
        name: "ฮานอย Extra",
        flag: "🇻🇳",
        sub: "ออกผล 21:00",
        isOpen: true,
        countdown: "11:15:42",
        barClass: "from-rose-600 to-yellow-500",
        href: "/bet?lottery=hanoi_extra",
      },
      {
        id: "laos_gov",
        name: "ลาว (รัฐบาล)",
        flag: "🇱🇦",
        sub: "ออกผล 20:20 น.",
        isOpen: false,
        result: { top3: "181", bot2: "51" },
        barClass: "from-red-600 via-blue-700 to-green-500",
        href: "/bet?lottery=laos_gov",
      },
      {
        id: "laos_vip",
        name: "ลาว VIP",
        flag: "🇱🇦",
        sub: "ออกผล 20:45 น.",
        isOpen: true,
        countdown: "10:02:55",
        barClass: "from-red-500 to-blue-500",
        href: "/bet?lottery=laos_vip",
      },
      {
        id: "laos_star",
        name: "ลาว Star",
        flag: "🇱🇦",
        sub: "ออกผล 21:30 น.",
        isOpen: true,
        countdown: "11:47:00",
        barClass: "from-blue-700 to-red-500",
        href: "/bet?lottery=laos_star",
      },
      {
        id: "malay",
        name: "มาเลเซีย",
        flag: "🇲🇾",
        sub: "ออกผล 19:00 น.",
        isOpen: false,
        result: { top3: "230", bot2: "31" },
        barClass: "from-red-600 to-blue-800",
        href: "/bet?lottery=malay",
      },
    ],
  },
  {
    id: "thai_stock",
    label: "หวยหุ้นไทย",
    emoji: "📈",
    gradient: "from-sky-600 to-cyan-400",
    badge: "SET เช้า · บ่าย · ปิด",
    items: [
      {
        id: "set_morn",
        name: "หุ้นไทย เช้า",
        flag: "📈",
        sub: "ตลาดเช้า 11:00",
        isOpen: false,
        result: { top3: "394", bot2: "28" },
        barClass: "from-blue-600 to-cyan-400",
        href: "/bet?lottery=set_morn",
      },
      {
        id: "set_aft",
        name: "หุ้นไทย บ่าย",
        flag: "📊",
        sub: "ตลาดบ่าย 14:30",
        isOpen: false,
        result: { top3: "712", bot2: "85" },
        barClass: "from-cyan-600 to-blue-500",
        href: "/bet?lottery=set_aft",
      },
      {
        id: "set_close",
        name: "หุ้นไทย ปิด",
        flag: "📉",
        sub: "ตลาดปิด 16:30",
        isOpen: true,
        countdown: "06:14:10",
        barClass: "from-blue-500 to-indigo-500",
        href: "/bet?lottery=set_close",
      },
    ],
  },
  {
    id: "foreign_stock",
    label: "หวยหุ้นต่างประเทศ",
    emoji: "🌐",
    gradient: "from-violet-600 to-indigo-400",
    badge: "นิเคอิ · จีน · ดาวโจนส์",
    items: [
      {
        id: "nikkei_morn",
        name: "นิเคอิ เช้า",
        flag: "🇯🇵",
        sub: "ตลาดญี่ปุ่น 09:00",
        isOpen: false,
        result: { top3: "523", bot2: "16" },
        barClass: "from-red-500 to-white",
        href: "/bet?lottery=nikkei_morn",
      },
      {
        id: "nikkei_aft",
        name: "นิเคอิ บ่าย",
        flag: "🇯🇵",
        sub: "ตลาดญี่ปุ่น 14:00",
        isOpen: false,
        result: { top3: "067", bot2: "91" },
        barClass: "from-white to-red-500",
        href: "/bet?lottery=nikkei_aft",
      },
      {
        id: "china_morn",
        name: "จีน เช้า",
        flag: "🇨🇳",
        sub: "ตลาดจีน 10:00",
        isOpen: false,
        result: { top3: "348", bot2: "74" },
        barClass: "from-red-600 to-yellow-400",
        href: "/bet?lottery=china_morn",
      },
      {
        id: "china_aft",
        name: "จีน บ่าย",
        flag: "🇨🇳",
        sub: "ตลาดจีน 14:00",
        isOpen: true,
        countdown: "04:38:22",
        barClass: "from-yellow-400 to-red-600",
        href: "/bet?lottery=china_aft",
      },
      {
        id: "hangseng_morn",
        name: "ฮั่งเส็ง เช้า",
        flag: "🇭🇰",
        sub: "ตลาดฮ่องกง 10:00",
        isOpen: false,
        result: { top3: "819", bot2: "33" },
        barClass: "from-red-600 to-gray-700",
        href: "/bet?lottery=hangseng_morn",
      },
      {
        id: "hangseng_aft",
        name: "ฮั่งเส็ง บ่าย",
        flag: "🇭🇰",
        sub: "ตลาดฮ่องกง 14:30",
        isOpen: true,
        countdown: "05:02:11",
        barClass: "from-gray-700 to-red-600",
        href: "/bet?lottery=hangseng_aft",
      },
      {
        id: "dowjones",
        name: "ดาวโจนส์",
        flag: "🇺🇸",
        sub: "ตลาดอเมริกา",
        isOpen: true,
        countdown: "13:55:44",
        barClass: "from-blue-700 to-red-600",
        href: "/bet?lottery=dowjones",
      },
      {
        id: "sg",
        name: "สิงคโปร์",
        flag: "🇸🇬",
        sub: "ตลาดสิงคโปร์",
        isOpen: false,
        result: { top3: "905", bot2: "35" },
        barClass: "from-red-600 to-white",
        href: "/bet?lottery=sg",
      },
    ],
  },
  {
    id: "yeekee_speed",
    label: "Speed ยี่กี",
    emoji: "⚡",
    gradient: "from-yellow-500 to-orange-500",
    badge: "รอบ 5 นาที",
    items: [
      {
        id: "yeekee",
        name: "Speed ยี่กี รอบ 1",
        flag: "⚡",
        sub: "รอบ 5 นาที",
        isOpen: true,
        countdown: "04:32",
        barClass: "from-yellow-500 to-orange-400",
        href: "/bet?lottery=yeekee",
      },
      {
        id: "yeekee_s2",
        name: "Speed ยี่กี รอบ 2",
        flag: "⚡",
        sub: "รอบ 5 นาที",
        isOpen: true,
        countdown: "09:18",
        barClass: "from-orange-500 to-yellow-400",
        href: "/bet?lottery=yeekee_s2",
      },
      {
        id: "yeekee_s3",
        name: "Speed ยี่กี รอบ 3",
        flag: "⚡",
        sub: "รอบ 5 นาที",
        isOpen: false,
        result: { top3: "452", bot2: "63" },
        barClass: "from-amber-500 to-orange-500",
        href: "/bet?lottery=yeekee_s3",
      },
    ],
  },
  {
    id: "yeekee_super",
    label: "Super ยี่กี",
    emoji: "⭐",
    gradient: "from-purple-600 to-pink-500",
    badge: "รอบพิเศษ VIP",
    items: [
      {
        id: "yeekee_vip",
        name: "Super ยี่กี VIP",
        flag: "🎰",
        sub: "รอบ 15 นาที",
        isOpen: true,
        countdown: "12:08",
        barClass: "from-purple-600 to-pink-400",
        href: "/bet?lottery=yeekee_vip",
      },
      {
        id: "yeekee_star",
        name: "Super ยี่กี Star",
        flag: "⭐",
        sub: "รอบ 5 นาที พิเศษ",
        isOpen: false,
        result: { top3: "452", bot2: "63" },
        barClass: "from-yellow-500 to-orange-400",
        href: "/bet?lottery=yeekee_star",
      },
    ],
  },
  {
    id: "slot",
    label: "Slot",
    emoji: "🎰",
    gradient: "from-rose-600 to-pink-400",
    badge: "สล็อตออนไลน์",
    items: [],
  },
  {
    id: "casino",
    label: "Casino",
    emoji: "🃏",
    gradient: "from-amber-600 to-yellow-400",
    badge: "บาคาร่า · รูเล็ต",
    items: [],
  },
  {
    id: "sport",
    label: "Sport",
    emoji: "⚽",
    gradient: "from-green-600 to-lime-400",
    badge: "แทงบอล · กีฬา",
    items: [],
  },
];

export const getCategoryById = (id: string) =>
  CATEGORIES.find((c) => c.id === id) ?? null;
